### ISSUE TITLE
Implementing Messages commands

### ISSUE THREAD

**Issue by Mo9a7i** [sudogroup/SudoSM#13]
**Is your feature request related to a problem? Please describe.**
need to implement the messages commands as part of the alpha release.

**Describe the solution you'd like**
Implement the following:
**Messages:**

- [x] clear [text-channel]: removes all messages in text-channel
- [x] prune [amount]: delete the last amount of messages
- [x] pin [text]: pins a text.
- [X] unpin [ALL OR portion of text]: unpins a message either by adding `ALL` or adding a portion of the word you want to delete, or many words, the script will look for pinned messages that have all the arguments you give.

**Comment by Mo9a7i** [comment]
@sudogroup/devs guys, the unpin command, what do you want it to unpin?
1. all messages
2. last pinned message
3. you type `!sudo unpin portion of the message` then it searches and unpins the found ones ?

**Comment by sudomaze** [comment]
I think the third option is better. Maybe, if you don't add any arguments, then you will remove all pinned messages in the channel. @MutlaqAldhbuiub what do you think?

**Comment by MutlaqAldhbuiub** [comment]
In my opinion the third option the most suitable.

**Comment by Mo9a7i** [comment]
Agree
Will do it tonight
