### ISSUE TITLE
Implementing Management Commands

### ISSUE THREAD

**Issue by MutlaqAldhbuiub** [sudogroup/SudoSM#16]
**Is your feature request related to a problem? Please describe.**
We need to add commands to manage the server

**Describe the solution you'd like**
Creating those commands:

- [x]  ban [user]: bans a user from the server
- [x]  uban [user]: unbans a user from the server
- [x]  kick [user]: removes a user from the server
- [ ]  mute [user] [time]: mutes a user from typing for time (minutes). By default, time is 10. **(need database for timed mute)**
- [x]  unmute [user]: unmutes a user from typing

**Comment by sudomaze** [comment]
I have completed all `ban`, `unban`, `kick`, `mute`, and `unmute`. I will wait for @Mo9a7i to merge his latest changes to master then I will pull it locally and merge it with my current changes before making a pull request.

As for `mute`, we need to set up a database to have a log for muting users for a certain time, so when the bot restarts/crashes, the bot can know to unmute people once their time is completed.

**Comment by Mo9a7i** [comment]
Whats happening
