### ISSUE TITLE
Implementing Channel Management Commands

### ISSUE THREAD

**Issue by MutlaqAldhbuiub** [sudogroup/SudoSM#24]
**Is your feature request related to a problem? Please describe.**
The bot doesn't have a way to create channels. In addition, it is beneficial to have the ability to specify to choose what's the type of the channel, e.g voice-channel, text-channel, announcement-channel.
**Describe the solution you'd like**
Implementing those commands:
- [x] mkcha [user]: creating a new channel it could be voice-channel, text-channel, announcement-channel, etc..
- [x] rmcha  [user]: remove the channel from the server.
- [x] mvcha [uesr] [update]: rename the channel.

**Comment by Mo9a7i** [comment]
- mkcha [name] [category]: creating a new channel it could be voice-channel, text-channel, announcement-channel, etc..
  او نخليه مثل اللينكس
  مثال
  `mkcha /STREAMERS/Salam Wallah` will add a channel called salam wallah under streamers category
  `mkcha Salam Wallah` will just create a new channel called salam wallah not under any category

-  rmcha [name]: remove the channel from the server.
-  mvcha [name] [new_name]: rename the channel.
   لو سوينا اللي فوق مثل اللينكس
   يصير نقدر نسوي كذا
   `mvcha "/STREAMERS/Salam Wallah" "/STREAMERS/Hala"`
   or
   `mvcha "/STREAMERS/Salam Wallah" "/boot/Hala Wallah"`

**Comment by Mo9a7i** [comment]
Just to note our discussion of making the sudo like a real linux sudo
creating channels by using mkdir command <https://discordapp.com/channels/696537024143818773/762043949048266774/765343363880714240>
addgroup -user -group

create a new role called sudoers
bin/bash for users
